//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicalPosition.SalesSystem.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomainEmail
    {
        public int DomainEmailId { get; set; }
        public int DomainId { get; set; }
        public string ContactEmail { get; set; }
    
        public virtual Domain Domain { get; set; }
    }
}
